controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

tasks:
    path: /tasks
    controller: App\Controller\TaskController::index

users:
    path: /register
    controller: App\Controller\UserController::register
