controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

tasks:
    path: /
    controller: App\Controller\TaskController::index

tasks_detail:
    path: /task/{id}
    controller: App\Controller\TaskController::detail

tasks_create:
    path: /create
    controller: App\Controller\TaskController::create

myTasks:
    path: /myTask
    controller: App\Controller\TaskController::myTask

register:
    path: /register
    controller: App\Controller\UserController::register

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
